"""update orders model

Revision ID: 94ae777b85a5
Revises: eb6fd3de76ee
Create Date: 2024-10-30 12:04:41.325889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ae777b85a5'
down_revision = 'eb6fd3de76ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('dish_id', sa.Integer(), nullable=False))
    op.drop_constraint('order_restaurant_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'order', 'dish', ['dish_id'], ['id'])
    op.drop_column('order', 'restaurant_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('restaurant_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_restaurant_id_fkey', 'order', 'restaurant', ['restaurant_id'], ['id'])
    op.drop_column('order', 'dish_id')
    # ### end Alembic commands ###
